# Generated by Django 2.1.2 on 2018-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoYouKnowMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
